services:
  - type: web
    name: Trueque_Market
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn TruequeMarket.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14

